---
#title: "Population projections for Luxembourg up to 2100"
output:
  html_document:
    self_contained: true
    #theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

library(shiny)
library(bs4Dash)
library(DT)
library(plotly)
library(htmltools)
library(fresh)
library(RCurl)
library(geodata)
library(raster)
library(sf)
library(dplyr)
library(tidyverse)
library(leaflet)
library(RColorBrewer)
library(shinyjs)
```

```{r}

fix_mojibake <- function(x) {
  if (!is.character(x)) return(x)
  
  y <- iconv(x, from = "UTF-8", to = "latin1", sub = "byte")
  Encoding(y) <- "UTF-8"
  ifelse(is.na(y) & !is.na(x), x, y)
}

df_pop2100 <- read.csv(text = getURL("https://raw.githubusercontent.com/MathieuScheffer/Projet-Hackaton/Resources/df_long.csv"))
df_pop2100$projection <- fix_mojibake(df_pop2100$projection)

df_pop2100 <- df_pop2100 %>%
  mutate(
    projection = recode(
      projection,
      "Historique"       = "Historical",
      "Ligne de base"    = "Baseline",
      "Forte migration"  = "High migration",
      "Faible fertilité" = "Low fertility",
      "Faible migration" = "Low migration",
      "Forte fertilité"  = "High fertility"
    )
  )

df_plot <- df_pop2100 %>%
  mutate(dash = ifelse(projection == "Historical", "solid", "dash"))

p <- plot_ly()

for (proj in unique(df_plot$projection)) {
  d <- df_plot %>% filter(projection == proj)
  p <- p %>%
    add_trace(
      data = d,
      x = ~year,
      y = ~population,
      type = "scatter",
      mode = "lines",
      name = proj,
      line = list(dash = unique(d$dash)),
      hoverinfo = "x+y+name"
    )
}

p <- p %>%
  layout(
    yaxis = list(title = "Number of people"),
    xaxis = list(title = "", showspikes = TRUE, spikemode = "across", spikedash = "solid", spikethickness = 1),
    hovermode = "x unified",
    hoverlabel = list(namelength = -1),
    shapes = list(
      list(
        type = "line",
        x0 = 2024, x1 = 2024,
        y0 = 0, y1 = 1,
        yref = "paper",
        line = list(color = "#000000", width = 2, dash = "dash")
      )
    ),
    annotations = list(
      list(
        x = 2024,
        y = 1,
        yref = "paper",
        xref = "x",
        text = "End of historical data",
        showarrow = FALSE,
        xanchor = "left",
        yanchor = "bottom"
      )
    )
  ) %>%
  config(displayModeBar = FALSE)

p

```