---
#title: "Share of Residents and Foreigners in pensions"
output:
  html_document:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

library(shiny)
library(bs4Dash)
library(DT)
library(plotly)
library(htmltools)
library(fresh)
library(RCurl)
library(geodata)
library(raster)
library(sf)
library(dplyr)
library(tidyverse)
library(leaflet)
library(RColorBrewer)
library(shinyjs)
```

```{r}

couleurs <- list("Resident" = "#1f77b4", "Foreign" = "#ff7f0e")

fix_mojibake <- function(x) {
  if (!is.character(x)) return(x)
  y <- iconv(x, from = "UTF-8", to = "latin1", sub = "byte")
  Encoding(y) <- "UTF-8"
  ifelse(is.na(y) & !is.na(x), x, y)
}

result_lm <- read.csv(text = getURL("https://raw.githubusercontent.com/MathieuScheffer/Projet-Hackaton/Resources/result_lm.csv"))
result_lm$Categorie <- fix_mojibake(result_lm$Categorie)
result_lm$Type <- fix_mojibake(result_lm$Type)

result_lm <- result_lm %>%
  mutate(
    Type = recode(
      Type,
      "Historique" = "Historical",
      "Prévision" = "Forecast"
    ),
    Categorie = recode(
      Categorie,
      "Resident" = "Resident",
      "Etranger" = "Foreign"
    )
  )


df_plot <- result_lm %>%
  mutate(Valeur = round(100 * Valeur, digits = 1)) %>%
  mutate(
    trace_name = paste(Categorie, "-", Type),
    dash = ifelse(Type == "Historical", "solid", "dash"),
    couleur = unlist(couleurs[Categorie])
  )

p <- plot_ly()

for (tn in unique(df_plot$trace_name)) {
  d <- df_plot %>% filter(trace_name == tn)
  p <- p %>%
    add_trace(
      data = d,
      x = ~Annee,
      y = ~Valeur,
      type = "scatter",
      mode = "lines",
      name = tn,
      line = list(color = unique(d$couleur), dash = unique(d$dash)),
      hoverinfo = "x+y+name"
    )
}

p <- p %>%
  layout(
    yaxis = list(title = "Breakdown", range = c(0, 100)),
    xaxis = list(title = ""),
    hovermode = "x unified",
    hoverlabel = list(namelength = -1),
    shapes = list(
      list(
        type = "line",
        x0 = 2023, x1 = 2023,
        y0 = 0, y1 = 100,
        yref = "y",
        line = list(color = "#000000", width = 2, dash = "dash")
      )
    ),
    annotations = list(
      list(
        x = 2023,
        y = 100,
        yref = "y",
        xref = "x",
        text = "End of historical data",
        showarrow = FALSE,
        xanchor = "left",
        yanchor = "bottom"
      )
    )
  ) %>%
  config(displayModeBar = FALSE)

p

```